name: Build & Deploy Docs (via gh-pages)

on:
  push:
    branches:
      - main # Only run when pushing to your main branch (or 'master')
  workflow_dispatch:

# The 'permissions' block is crucial for the official actions to work!
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # Allow reading source code
      pages: write       # Allow writing to the GitHub Pages site
      id-token: write    # Required for the deploy-pages action

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements_docs.txt

      - name: Clean previous Sphinx build
        run: rm -rf docs/_build/html

      - name: Build Sphinx docs
        # Note: The output folder is docs/_build/html
        working-directory: docs
        run: sphinx-build -b html . _build/html

      # ----------------------------------------------------
      # New Steps for Official GitHub Pages Deployment
      # ----------------------------------------------------

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This path must match the Sphinx build output exactly
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # Note: This action automatically targets the 'github-pages' environment
        # and deploys the uploaded artifact.